all:
  vars:
    app_name: typo3
    compose_projects_root: /opt/docker/compose
  children:
    dev:
      hosts:
        dev:
          ansible_host: dev-host
          ansible_user: user
    test:
      hosts:
        test:
          ansible_host: test-host
          ansible_user: user
    live:
      hosts:
        live:
          ansible_host: live-host
          ansible_user: user
